### ISSUE TITLE
Road Map

### ISSUE THREAD

**Issue by dpo** [optimizers/nlpy#18]
Here are some of the steps that need to happen before a release:
- [ ] Add tests for everything
- [ ] Move factorizations to CySparse
- [ ] Move iterative methods to PyKrylov
- [ ] Move NLPy to the `optimizers` organization
- [ ] Integrate the simplified slack model
- [ ] Use `try` blocks to check for optional dependencies at run time
- [ ] `precon/pycfs` will be replaced by `lldl`
- [ ] ensure all code is PEP8 and PEP257 compliant

@syarra @counterclocker

**Comment by syarra** [comment]
What do we do with `propack`?

@dpo

**Comment by dpo** [comment]
I've been using Propack to approximate eigenvalues or singular values. For example I approximate the smallest eigenvalue of H and then shift H as in modified Newton. If it doesn't fit anywhere, it could be in its own module.
